[package]
name = "hello_world"
version.workspace = true
edition.workspace = true

# 配置为裸机目标（无标准库）
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

# 禁用标准库
[dependencies]
